version: 2.1
orbs:
  slack: circleci/slack@3.4.0
jobs:
  build-integration:
    docker:
      - image: gcr.io/windmill-public-containers/tilt-integration-ci@sha256:75e5d29da4ff2b06f5ae356b70935155499901218cdcabbbb7cebb31410c578c
    steps:
      - checkout
      - run: echo 'export PATH=~/go/bin:$PATH' >> $BASH_ENV
      - run: make integration
      - store_test_results:
          path: test-results
      - slack/notify-on-failure:
          only_for_branches: master

workflows:
  version: 2
  build:
    jobs:
      - build-integration
